// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trabalho_AD;

#nullable disable

namespace Trabalho_AD.Migrations
{
    [DbContext(typeof(GeralContext))]
    [Migration("20240622175925_Trabalho-AD")]
    partial class TrabalhoAD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trabalho_AD.Model.Cliente", b =>
                {
                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("idVeiculo")
                        .HasColumnType("int");

                    b.Property<string>("tipoContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nome");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Trabalho_AD.Model.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("int");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<int>("PrazoDias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdVeiculo");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Trabalho_AD.Model.Veiculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ano")
                        .HasColumnType("int");

                    b.Property<int>("idMarca")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("Trabalho_AD.Model.Reserva", b =>
                {
                    b.HasOne("Trabalho_AD.Model.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("IdVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
